---
title: "TrajectoryAnalysis_Script"
output: html_document
date: "2024-11-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Script for Video #2 Draft

This video will go over the basics behind running a trajectory analysis using the 'timeseriesTrajectories' R package by Bilintoh, along with additional features 
from the 'terra' and 'raster' packages. It will follow with an example using 
mangrove data in Indonesia.
NOTE: the timeseriesTrajectories package uses most of these libraries within it. 
Installing the timeseriesTrajectories package will come with many libraries that 
it utilizes.


For a detailed description of Trajectory Analysis, review our video linked in 
the description and shown at the end of this video. We will also link our Rmarkdown 
that is shown throughout the duration of this tutorial, the Rstudio website, and 
the RTools download site in the description.


First, installing R and Rstudio. You will go to this site, linked in the 
description, and click both of the blue boxes. You can think of RStudio as the 
interface and R as the bones.

<https://posit.co/download/rstudio-desktop/>
  
  
  
  
  
  
  
### NOTE: Feel free to skip this step, if you receive an RTools error later on, 
### then you can come back here to see how the install process works.


If you do not have RTools installed, you will receive an error when you try to 
run certain functions from this tutorial. Here is the link to the RTools page:

<https://cran.r-project.org/bin/windows/Rtools/>
  
Or to go straight to RTools 4.4:
<https://cran.r-project.org/bin/windows/Rtools/rtools44/rtools.html>

Click the blue text 'Rtools44 installer'. After the installer has been 
downloaded click it and go through the wizard. We suggest leaving everything as 
it is, this will give you a simple base install.





### After you've installed, You will open a new R Script file

File -> New File -> R Script


Some R basics:
Updates - Every time I launch RStudio, there is typically an update that can be 
done for the software. It is best practice to avoid updating constantly. You do 
not want to be the test hamster that finds out the new update breaks one of the 
R packages you are using. You should do a thorough review online and ensure other 
users are not experiencing issues with the update.

Second, calling variables. Although R allows users to use an '=' sign, this 
creates a global variable, also not best practice. Instead use '<-' to declare 
a new variable. i.e.,

Profit <- df['Sales'] - df['Cost']

This is the save button, run highlighted/selected line, run all lines.

To speed up running lines of code, you can instead use ctrl + enter and it will 
be the same as running the selected line (wherever your text cursor is).

##### POSSIBLY SHOW HOW TO CONNECT TO GITHUB?? #####


### Now we can start downloading packages.

Run the following:


```
install.packages('devtools')
devtools::install_github('bilintoh/timeseriesTrajectories')
```

The second line will give a prompt with additional directions: when prompted 
type '1' and hit enter, this will update all necessary packages that 
timeseriesTrajectories uses.


### Background on our example data
We are reviewing the Mahakam Delta in Indonesia. Specifically, how mangroves 
transition to Shrimp ponds. Having trajectories of the Mahakam Mangroves can 
help give insight to what the future land may look like, impacting shrimp 
farmers, locals, and the ecosystem as a whole.


Bilintoh's README example, link in description, has pre-made binary files and 
are already in TIF form. However, our data initially is not binary and is in 
Raster. We will go through the steps of making the data binary and then formatting 
into a tif file. And then put the TIF files into one multilayer TIF file, which 
is what the 'timeseriesTrajectories' package requires to run.

DISCLAIMER. You can also have vector data. This can be formatted to binary and 
then to TIF as well in R{{{{{{MAYBE?}}}}}}}, however, we will not go over this. 
There is a link in the description that provides a first-step guide to performing 
these operations. We have not attempted it and cannot guarantee it to be 100% 
accurate.




# TO-DO:
Follow Rufai's file from here...







Ending:



Watch our video that describes the basic concepts behind trajectory analysis 
and the key takeaways from Bilintoh, et al. (2022??): link

Contributors to this project are:
Rufai Omowunmi Balogun (GitHub: Ruphai)
Sunita Phuyal (GitHub: MeSunita)
Daniel Neau (GitHub: danieljneau)
Harrison Leduc (GitHub: HLed12)
